@Path = http://172.20.10.6:25565

### create user
POST {{Path}}/user
Content-Type: application/json

{
    "name": "test",
    "password": "validpassword"
}



### get user
GET {{Path}}/users



### login
POST {{Path}}/user/login
Content-Type: application/json

{
    "name": "test",
    "password": "validpassword"
}