@Port = 25565
@Path = http://172.20.10.7:{{Port}}
@Path2 = http://10.66.99.180:{{Port}}


### create user
POST {{Path2}}/users
Content-Type: application/json

{
    "name": "test",
    "password": "validpassword"
}



### get user
GET {{Path2}}/users



### login
POST {{Path2}}/users/login
Content-Type: application/json

{
    "name": "test",
    "password": "validpassword"
}